aliases: {}
substitute-path: []
max-string-len: 10000
max-array-values: 50
show-location-expr: false
source-list-line-color: 34
source-list-arrow-color: ""
source-list-keyword-color: ""
source-list-string-color: ""
source-list-number-color: ""
source-list-comment-color: ""
debug-info-directories:
- /usr/lib/debug/.build-id
